apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "payment-service.selectorLabels" . | nindent 4 }}
