# Default values for payment-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

fullname: "payment-service"

image:
  repository: "ebinsu/payment-service"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "17"

podAnnotations: {
  prometheus.io/scrape: "true"
    prometheus.io/port: "9464"
    prometheus.io/path: "/metrics"
}

service:
  type: ClusterIP
  port: 80

selectorLabels:
  app: order-service
  component: java